name: Sync Forked Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Sync Forked Repo
        uses: humonnom/sync-fork@v0.1.0-alpha.5
        with:
          upstream_repository_owner: 'Profile-Image-Generator'
          upstream_repository_name: 'linked-in'
          forked_repository_owner: 'humonnom'
          forked_repository_name: 'linked-in'
