name: Auto Sync Forked Repo

on:
  push:
    branches: 
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Auto Sync Forked Repo
        uses: humonnom/auto-sync-forked-repo@v0
